# alacritty.toml
# By OldJobobo (https://github.com/OldJobobo)
# 

[window]
opacity = 0.888

[colors]
[colors.primary]
background = "#080706"
foreground = "#9e9286"

[colors.normal]
black   = "#080706"
red     = "#96423c"
green   = "#51604f"
yellow  = "#a67a43"
blue    = "#5a6674"
magenta = "#7b5a6a"
cyan    = "#8c6f4b"
white   = "#9e9286"

[colors.bright]
black   = "#6f665f"
red     = "#a5342f"
green   = "#667863"
yellow  = "#c08b4a"
blue    = "#7a8796"
magenta = "#967284"
cyan    = "#c4ab84"
white   = "#d0c3b4"

[colors.cursor]
text   = "#080706"
cursor = "#9e9286"

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
