# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[main]
font=monospace:size=11
pad=14x14 center

[colors-dark]
alpha = 0.888
foreground = d0c3b4
background = 080706

cursor = d0c3b4 080706

selection-foreground = 080706
selection-background = 5a6674

regular0 = 080706
regular1 = 96423c
regular2 = 51604f
regular3 = a67a43
regular4 = 5a6674
regular5 = 7b5a6a
regular6 = 8c6f4b
regular7 = 9e9286

bright0 = 6f665f
bright1 = a5342f
bright2 = 667863
bright3 = c08b4a
bright4 = 7a8796
bright5 = 967284
bright6 = c4ab84
bright7 = f7f1ea
