# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #080706
foreground            #d0c3b4
background_opacity 0.888

# black
color0  #080706
color8  #6f665f

# red
color1  #96423c
color9  #a5342f

# green
color2  #51604f
color10 #667863

# yellow
color3  #a67a43
color11 #c08b4a

# blue
color4  #5a6674
color12 #7a8796

# magenta
color5  #7b5a6a
color13 #967284

#cyan
color6  #8c6f4b
color14 #c4ab84

#white
color7  #9e9286
color15 #f7f1ea

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
